CREATE TABLE DIVISION_MASTER(
   DIVISION_ID INT PRIMARY KEY NOT NULL,
   DIVISION_NAME TEXT NOT NULL
);

CREATE TABLE STORE_MASTER(
   STORE_ID INT PRIMARY KEY NOT NULL,
   BRAND_NAME VARCHAR(255) NOT NULL,
   ADDRESS VARCHAR(255) NOT NULL,
   STORE_TYPE VARCHAR(255),
   TIME_ZONE VARCHAR(50)
);

CREATE TABLE DIVISION_STORE_MASTER(
   DIVISION_STORE_ID INT PRIMARY KEY NOT NULL,
   DIVISION_ID INT NOT NULL,
   STORE_ID INT NOT NULL,
   ACTIVE VARCHAR(50)
);


CREATE TABLE STORE_AISLE_MASTER(
   STORE_AISLE_ID INT PRIMARY KEY NOT NULL,
   DIVISION_STORE_ID INT NOT NULL,
   AISLE_NO INT NOT NULL
);

CREATE TABLE SCREEN_MASTER(
   SCREEN_ID INT PRIMARY KEY NOT NULL,
   SCREEN_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE WORKFLOW_MASTER(
   WORKFLOW_ID INT PRIMARY KEY NOT NULL,
   WORKFLOW_NAME VARCHAR(255) NOT NULL,
   WORKFLOW_DESE VARCHAR(255) NOT NULL
);

CREATE TABLE PRIORITY_MASTER(
   PRIORITY_ID INT PRIMARY KEY NOT NULL,
   PRIORITY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE REASONS_MASTER(
   REASON_ID INT PRIMARY KEY NOT NULL,
   REASON_DESC VARCHAR(255) NOT NULL
);


CREATE TABLE SHIFT_TIMINGS_MASTER(
   SHIFT_ID INT PRIMARY KEY NOT NULL,
   SHIFT_START_TIME VARCHAR(255) NOT NULL,
   SHIFT_END_TIME VARCHAR(255) NOT NULL
);


CREATE TABLE EMPLOYEE_MASTER(
   EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
   EMPLOYEE_NAME VARCHAR(255) NOT NULL,
   STATUS VARCHAR(255) NOT NULL,
   AVAILABLE_DATE DATE NOT NULL,
   WORKING_HOURS VARCHAR(50) NOT NULL,
   SHIFT_ID INT NOT NULL,
   DIVISION_STORE_ID INT NOT NULL
);


CREATE TABLE STORE_SCHEDULED_TRUCK_DETAILS(
   TRUCK_ID INT PRIMARY KEY NOT NULL,
   ROUTE_NO VARCHAR(255) NOT NULL,
   DIVISION_STORE_ID INT NOT NULL,
   PALLETS INT NOT NULL,
   ETA VARCHAR(50) NOT NULL,
   SHIFT_ID INT NOT NULL,
   WINDOW VARCHAR(50) NOT NULL,
   SCHEDULED_TIME VARCHAR(255) NOT NULL
);

CREATE TABLE TRUCK_ARRIVALS_TRACKER(
	ARRIVAL_ID INT PRIMARY KEY NOT NULL,
	TRUCK_ID INT NOT NULL,
	SEAL_NO VARCHAR(50) NOT NULL,
	FREIGHT_STATUS VARCHAR(50) NOT NULL,
	ARRIVED_TIME VARCHAR(50) NOT NULL
);

CREATE TABLE IMAGES_MASTER(
	IMAGE_ID INT PRIMARY KEY NOT NULL,
	IMAGE BYTEA NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_DATE VARCHAR(255) NOT NULL
);

CREATE TABLE ARRIVED_TRUCK_IMAGES(
	ARRIVED_TRUCK_IMAGE_ID INT PRIMARY KEY NOT NULL,
	ARRIVAL_ID INT NOT NULL,
	IMAGE_ID INT NOT NULL,
	COMMENTS VARCHAR(255) NOT NULL
);

CREATE TABLE STORE_INVENTORY_DETAILS(
	INVENTORY_ID INT PRIMARY KEY NOT NULL,
	TRUCK_ID INT NOT NULL,
	STORE_AISLE_ID INT NOT NULL,
	INVENTORY_TYPE VARCHAR(50) NOT NULL,
	CASE_QTY INT NOT NULL
);

CREATE TABLE STORE_INVENTORY_CHANGES_TRACKER(
	INVENTORY_CHANGES_TRACKER_ID INT PRIMARY KEY NOT NULL,
	INVENTORY_ID INT NOT NULL,
	PREVIOUS_CASE_QTY INT NOT NULL,
	REASON_ID INT NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	CREATED_DATE VARCHAR(255) NOT NULL
);

CREATE TABLE TASKS_MASTER(
	TASK_ID INT PRIMARY KEY NOT NULL,
	TASK_NAME VARCHAR(255) NOT NULL,
	TASK_STATUS VARCHAR(255) NOT NULL,
	TASK_DATE VARCHAR(255) NOT NULL,
	TIMER_STATUS VARCHAR(255) NOT NULL,
	TASK_TIMESTAMP VARCHAR(255) NOT NULL,
	TRUCK_ID INT NOT NULL,
	ACTUAL_TIME VARCHAR(255) NOT NULL,
	ESTIMATED_TIME VARCHAR(255) NOT NULL,
	CASE_QTY INT NOT NULL,
	PRIORITY_ID INT NOT NULL,
	PROCESS VARCHAR(255) NOT NULL,
	STOCKING_RATE VARCHAR(255) NOT NULL,
	DIVISION_STORE_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL
);

CREATE TABLE WORK_FLOW_AUDIT(
	WORK_FLOW_AUDIT_ID INT PRIMARY KEY NOT NULL,
	ACTIVITY_ID VARCHAR(255) NOT NULL,
	WORK_FLOW_ID INT NOT NULL,
	REQUEST_PROCESSED_BY_MS VARCHAR(50) NOT NULL,
	REQUEST_PROCESSED_BY_ORSOLVER VARCHAR(50) NOT NULL,
	DATA_MERGED_TO_TASKLIST VARCHAR(50) NOT NULL,
	LAST_UPDATED_BY VARCHAR(255) NOT NULL,
	LAST_UPDATED_DATE VARCHAR(255) NOT NULL
);
